#!/usr/bin/env python3
"""Deterministic delivery hook — locate the deliverable, send it, record it.

The final fulfillment stage's task body (generated by the engine) instructs its
worker to run this adapter. It closes the last "silent success" hole in the
pipeline: setting an item's status notifies no one, and prose instructions to
"send the deliverable" historically went unexecuted. This adapter either sends
through the configured Hermes delivery channel or fails loudly.

    python delivery_actions.py --config triage.yaml <slug> [--file <path>] [--dry-run]

Deliverable resolution, in order:
  1. `--file` (absolute or workspace-relative; must live inside the item's
     persistent workspace).
  2. `paths.<path>.deliverable` from triage.yaml — a filename or glob resolved
     inside the workspace that must match exactly one file.
  3. A single `deliverable.*` / `DELIVERABLE.*` file in the workspace root.
Anything ambiguous or missing is a hard, listed failure — the worker blocks its
task with the JSON error instead of improvising.

Delivery uses the supported Hermes messaging surface: `hermes send --to
<gate.target> --file <deliverable>`, the same channel contract as the proposal
send. On success the item is marked `delivered` and the triage root (plus the
running task, when known) gets a board comment.

`--dry-run` resolves and validates everything, prints the exact command, and
mutates nothing — the synthetic eval uses it.

Environment: TRIAGE_CONFIG, TRIAGE_VAULT_DIR, HERMES_KANBAN_DB, HERMES_HOME,
HERMES_KANBAN_TASK (used only to comment on the running task).
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from engine.config import TriageConfig
from engine.engine import TriageEngine
from engine.item_vault import ItemVault, utc_now_iso
from engine.kanban_store import KanbanStore
from proposal_actions import (
    board_db,
    die_backend,
    die_input,
    die_state,
    first_linked_task,
    item_slug,
    vault_dir,
)

DELIVERABLE_FALLBACK_GLOBS = ("deliverable.*", "DELIVERABLE.*")


def load_config(config_path: str | Path | None = None) -> TriageConfig:
    return TriageConfig.load(config_path or os.environ.get("TRIAGE_CONFIG") or "triage.yaml")


def resolve_deliverable(workspace: Path, pattern: str | None, explicit: str | None) -> Path:
    """Deterministically pick the file to send, or raise with the evidence."""
    if explicit:
        candidate = Path(explicit)
        if not candidate.is_absolute():
            candidate = workspace / candidate
        candidate = candidate.resolve()
        if not candidate.is_file():
            raise FileNotFoundError(f"--file {explicit!r} does not exist under {workspace}.")
        if workspace != candidate and workspace not in candidate.parents:
            raise ValueError(f"--file {explicit!r} resolves outside the item workspace {workspace}.")
        return candidate

    if not workspace.is_dir():
        raise FileNotFoundError(
            f"Item workspace {workspace} does not exist; fulfillment stages must write there."
        )

    patterns = [pattern] if pattern else list(DELIVERABLE_FALLBACK_GLOBS)
    matches: list[Path] = []
    for glob_pattern in patterns:
        matches.extend(p for p in sorted(workspace.glob(glob_pattern)) if p.is_file())
    if len(matches) == 1:
        return matches[0].resolve()

    listing = sorted(p.name for p in workspace.iterdir())[:20]
    if not matches:
        raise FileNotFoundError(
            f"No deliverable matched {patterns} in {workspace}. Set `paths.<path>.deliverable` "
            f"in triage.yaml or pass --file. Workspace contains: {listing}."
        )
    raise ValueError(
        f"Deliverable pattern {patterns} is ambiguous in {workspace}: "
        f"{[m.name for m in matches]}. Set a more specific `paths.<path>.deliverable` or pass --file."
    )


def action_deliver(
    reference: str,
    config_path: str | Path | None = None,
    *,
    explicit_file: str | None = None,
    dry_run: bool = False,
    task_id: str | None = None,
) -> dict[str, Any]:
    config = load_config(config_path)
    slug = item_slug(reference, config)
    vault = ItemVault(vault_dir(config))
    engine = TriageEngine(config, vault)

    item = vault.load(slug)
    fm = item.frontmatter
    if fm.get("status") == "delivered":
        return {"ok": True, "action": "deliver", "slug": slug, "already_delivered": True,
                "delivered_at": fm.get("delivered_at")}
    if fm.get("status") != "approved":
        die_state(
            f"Item {slug} is {fm.get('status')!r}; delivery requires an `approved` item. "
            "The human gate is real — do not deliver unapproved work."
        )
    path_name = fm.get("path")
    if path_name not in config.paths:
        die_state(f"Item {slug} has invalid `path`: {path_name!r}. Known: {sorted(config.paths)}.")
    if not config.gate.target:
        die_state("gate.target is not configured in triage.yaml; nowhere to deliver.")

    workspace = engine.workspace_for(path_name, slug)
    deliverable = resolve_deliverable(
        workspace, config.get_path(path_name).deliverable, explicit_file
    )

    executable = shutil.which("hermes")
    command = [executable or "hermes", "send", "--to", config.gate.target, "--file", str(deliverable)]
    result: dict[str, Any] = {
        "ok": True,
        "action": "deliver",
        "pipeline_id": config.pipeline_id,
        "slug": slug,
        "path": path_name,
        "deliverable": str(deliverable),
        "target": config.gate.target,
        "command": command,
    }
    if dry_run:
        result["dry_run"] = True
        return result

    if not executable:
        die_backend("Hermes executable is unavailable; cannot send the deliverable.")
    proc = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if proc.returncode:
        detail = proc.stderr.strip() or proc.stdout.strip() or f"exit {proc.returncode}"
        die_backend(f"hermes send failed: {detail}")

    fm["status"] = "delivered"
    fm["delivered_at"] = utc_now_iso()
    fm["deliverable"] = str(deliverable)
    item.body = item.body.rstrip() + (
        f"\n\n## {utc_now_iso()}\n\n📦 **Delivered** `{deliverable.name}` to `{config.gate.target}`.\n"
    )
    vault.save(item)

    # Best-effort audit comments; a board hiccup must not un-deliver the item.
    warnings: list[str] = []
    note = f"📦 Delivered `{deliverable.name}` for `{slug}` to `{config.gate.target}`."
    try:
        store = KanbanStore(board_db(config))
        conn = store.connect()
        try:
            for comment_target in {t for t in (first_linked_task(fm), task_id) if t}:
                store.comment(conn, comment_target, author="hermes-triage:delivery", body=note)
            conn.commit()
        finally:
            conn.close()
    except Exception as exc:  # noqa: BLE001 - delivery already succeeded
        warnings.append(f"delivered, but board comment failed: {type(exc).__name__}: {exc}")
    if warnings:
        result["warnings"] = warnings
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="delivery_actions", description=__doc__)
    parser.add_argument("--config", default=os.environ.get("TRIAGE_CONFIG") or "triage.yaml")
    parser.add_argument("slug", help="Item slug or pipeline-qualified reference (<pipeline>:<slug>).")
    parser.add_argument("--file", default=None, help="Explicit deliverable path inside the item workspace.")
    parser.add_argument("--task-id", default=os.environ.get("HERMES_KANBAN_TASK"),
                        help="Running task id for the audit comment (dispatcher-injected).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Resolve and validate everything; send nothing, mutate nothing.")
    args = parser.parse_args(argv)
    try:
        result = action_deliver(
            args.slug, args.config,
            explicit_file=args.file, dry_run=args.dry_run, task_id=args.task_id,
        )
    except SystemExit:
        raise
    except (ValueError, FileNotFoundError) as exc:
        die_state(str(exc))
        return 2
    except Exception as exc:  # pragma: no cover - defensive
        die_backend(f"Unhandled error: {type(exc).__name__}: {exc}")
        return 3
    print(json.dumps(result, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
