#!/usr/bin/env python3
"""Deterministic gate-send hook — proposals and deliverables, one message each.

Task bodies generated by the engine instruct workers to run this adapter for
BOTH sends that cross the human gate. It closes two "silent failure" holes:
setting an item's status notifies no one, and raw `hermes send --file` sends
file *contents as message text*, which Discord chunks into a rapid burst of
2000-char messages — long proposals reliably trip Discord's rate limit that
way. This adapter instead sends ONE message with the file as a native
attachment (`MEDIA:<path>`), retries a bounded number of times on a 429, and
otherwise fails loudly.

    python delivery_actions.py --config triage.yaml deliver       <slug> [--file <path>] [--dry-run]
    python delivery_actions.py --config triage.yaml send-proposal <slug> [--file <path>] [--dry-run] [--resend]

(The old no-subcommand form `delivery_actions.py <slug>` still means `deliver`,
for task cards created before the split.)

Deliverable resolution, in order:
  1. `--file` (absolute or workspace-relative; must live inside the item's
     persistent workspace).
  2. `paths.<path>.deliverable` from triage.yaml — a filename or glob resolved
     inside the workspace that must match exactly one file.
  3. A single `deliverable.*` / `DELIVERABLE.*` file in the workspace root.
Anything ambiguous or missing is a hard, listed failure — the worker blocks its
task with the JSON error instead of improvising.

Proposal resolution: `--file`, else `<workspace_root>/proposals/<slug>.md` —
the exact path the propose task body tells its worker to render to.

Both sends use the supported Hermes messaging surface (`hermes send`) with a
short deterministic caption plus the file attached, so one adapter call is one
platform message regardless of file length. On a 429 the adapter sleeps
(15s → 45s → 120s) and retries; after that it exits non-zero and the worker
blocks with the JSON error — workers never hand-roll retry loops (an
improvised retry burst is what escalates a per-channel limit into a tripped
global bucket).

`--dry-run` resolves and validates everything, prints the exact command, and
mutates nothing — the synthetic eval uses it.

Environment: TRIAGE_CONFIG, TRIAGE_VAULT_DIR, HERMES_KANBAN_DB, HERMES_HOME,
HERMES_KANBAN_TASK (used only to comment on the running task).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from engine.config import TriageConfig
from engine.engine import TriageEngine
from engine.item_vault import ItemVault, utc_now_iso
from engine.kanban_store import KanbanStore
from proposal_actions import (
    append_note,
    board_db,
    die_backend,
    die_input,
    die_state,
    first_linked_task,
    item_slug,
    vault_dir,
)

DELIVERABLE_FALLBACK_GLOBS = ("deliverable.*", "DELIVERABLE.*")

# Discord's hard message cap is 2000 chars; a caption under this limit rides on
# the attachment message itself (hermes `_media_caption_split`), so the whole
# send stays a single platform message. Other platforms are no stricter here.
GATE_CAPTION_LIMIT = 1800

# Bounded backoff between attempts when the platform answers 429. Three sleeps
# → four attempts total, then a hard failure the worker blocks with.
RATE_LIMIT_RETRY_DELAYS = (15, 45, 120)
_RATE_LIMIT_RE = re.compile(r"\b429\b|rate.?limit", re.IGNORECASE)

# Statuses whose gate decision is already made — never (re)send a proposal.
PROPOSAL_FORBIDDEN_STATUSES = {
    "approved", "delivered", "shelved_by_human", "shelved_below_threshold",
}


def load_config(config_path: str | Path | None = None) -> TriageConfig:
    return TriageConfig.load(config_path or os.environ.get("TRIAGE_CONFIG") or "triage.yaml")


def resolve_deliverable(workspace: Path, pattern: str | None, explicit: str | None) -> Path:
    """Deterministically pick the file to send, or raise with the evidence."""
    if explicit:
        candidate = Path(explicit)
        if not candidate.is_absolute():
            candidate = workspace / candidate
        candidate = candidate.resolve()
        if not candidate.is_file():
            raise FileNotFoundError(f"--file {explicit!r} does not exist under {workspace}.")
        if workspace != candidate and workspace not in candidate.parents:
            raise ValueError(f"--file {explicit!r} resolves outside the item workspace {workspace}.")
        return candidate

    if not workspace.is_dir():
        raise FileNotFoundError(
            f"Item workspace {workspace} does not exist; fulfillment stages must write there."
        )

    patterns = [pattern] if pattern else list(DELIVERABLE_FALLBACK_GLOBS)
    matches: list[Path] = []
    for glob_pattern in patterns:
        matches.extend(p for p in sorted(workspace.glob(glob_pattern)) if p.is_file())
    if len(matches) == 1:
        return matches[0].resolve()

    listing = sorted(p.name for p in workspace.iterdir())[:20]
    if not matches:
        raise FileNotFoundError(
            f"No deliverable matched {patterns} in {workspace}. Set `paths.<path>.deliverable` "
            f"in triage.yaml or pass --file. Workspace contains: {listing}."
        )
    raise ValueError(
        f"Deliverable pattern {patterns} is ambiguous in {workspace}: "
        f"{[m.name for m in matches]}. Set a more specific `paths.<path>.deliverable` or pass --file."
    )


def resolve_proposal_file(config: TriageConfig, slug: str, explicit: str | None) -> Path:
    """The rendered proposal to attach — explicit --file, else the canonical path."""
    if explicit:
        candidate = Path(explicit)
        if not candidate.is_absolute():
            candidate = Path(config.hermes.project_root) / candidate
        candidate = candidate.resolve()
        if not candidate.is_file():
            raise FileNotFoundError(f"--file {explicit!r} does not exist.")
        return candidate
    candidate = (config.workspace_path / "proposals" / f"{slug}.md").resolve()
    if not candidate.is_file():
        raise FileNotFoundError(
            f"No rendered proposal at {candidate}. Render the proposal there first "
            "(the propose task body names this exact path), then re-run send-proposal."
        )
    return candidate


# --------------------------------------------------------------------------- #
# the single-message gate send
# --------------------------------------------------------------------------- #


def gate_send_command(target: str, caption: str, attachment: Path) -> list[str]:
    """One `hermes send`: caption text + `MEDIA:` tag = one message, file attached.

    The backticked path form is the one hermes' MEDIA extractor accepts verbatim
    (and it survives spaces). Keeping the caption under GATE_CAPTION_LIMIT keeps
    hermes on its single-message caption path instead of chunked text delivery.
    """
    if len(caption) > GATE_CAPTION_LIMIT:
        raise ValueError(
            f"Gate caption is {len(caption)} chars (limit {GATE_CAPTION_LIMIT}); captions are "
            "composed deterministically and must stay short — the full content rides in the attachment."
        )
    message = f"{caption}\nMEDIA:`{attachment}`"
    return [shutil.which("hermes") or "hermes", "send", "--to", target, message]


def run_gate_send(command: list[str]) -> dict[str, Any]:
    """Execute the send with bounded 429 backoff; die loudly on anything else."""
    if not shutil.which("hermes"):
        die_backend("Hermes executable is unavailable; cannot send to the gate.")
    attempts = 0
    while True:
        attempts += 1
        proc = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")
        if proc.returncode == 0:
            return {"attempts": attempts}
        detail = proc.stderr.strip() or proc.stdout.strip() or f"exit {proc.returncode}"
        if _RATE_LIMIT_RE.search(detail) and attempts <= len(RATE_LIMIT_RETRY_DELAYS):
            time.sleep(RATE_LIMIT_RETRY_DELAYS[attempts - 1])
            continue
        die_backend(f"hermes send failed after {attempts} attempt(s): {detail}")


def deliverable_caption(config: TriageConfig, slug: str, path_name: str, deliverable: Path) -> str:
    reference = f"{config.pipeline_id}:{slug}"
    return f"📦 Deliverable for `{reference}` ({path_name} path): `{deliverable.name}` attached."


def proposal_caption(config: TriageConfig, slug: str, fm: dict[str, Any]) -> str:
    """Deterministic gate summary: everything needed to act without opening the file."""
    reference = f"{config.pipeline_id}:{slug}"
    title = str(fm.get("title") or slug).strip()
    if len(title) > 200:
        title = title[:197] + "..."
    parts = [f"📋 Proposal `{reference}` — {title}"]
    meta = [f"path `{fm['path']}`" if fm.get("path") else "", f"score {fm['score']}" if fm.get("score") is not None else ""]
    meta = [m for m in meta if m]
    if meta:
        parts.append(" | ".join(meta))
    parts.append("Full proposal attached.")
    parts.append(f"Reply: approve {reference} | shelve {reference}: <reason> | modify {reference}: <change>")
    return "\n".join(parts)


def action_deliver(
    reference: str,
    config_path: str | Path | None = None,
    *,
    explicit_file: str | None = None,
    dry_run: bool = False,
    task_id: str | None = None,
) -> dict[str, Any]:
    config = load_config(config_path)
    slug = item_slug(reference, config)
    vault = ItemVault(vault_dir(config))
    engine = TriageEngine(config, vault)

    item = vault.load(slug)
    fm = item.frontmatter
    if fm.get("status") == "delivered":
        return {"ok": True, "action": "deliver", "slug": slug, "already_delivered": True,
                "delivered_at": fm.get("delivered_at")}
    if fm.get("status") != "approved":
        die_state(
            f"Item {slug} is {fm.get('status')!r}; delivery requires an `approved` item. "
            "The human gate is real — do not deliver unapproved work."
        )
    path_name = fm.get("path")
    if path_name not in config.paths:
        die_state(f"Item {slug} has invalid `path`: {path_name!r}. Known: {sorted(config.paths)}.")
    if not config.gate.target:
        die_state("gate.target is not configured in triage.yaml; nowhere to deliver.")

    workspace = engine.workspace_for(path_name, slug)
    deliverable = resolve_deliverable(
        workspace, config.get_path(path_name).deliverable, explicit_file
    )

    caption = deliverable_caption(config, slug, path_name, deliverable)
    command = gate_send_command(config.gate.target, caption, deliverable)
    result: dict[str, Any] = {
        "ok": True,
        "action": "deliver",
        "pipeline_id": config.pipeline_id,
        "slug": slug,
        "path": path_name,
        "deliverable": str(deliverable),
        "target": config.gate.target,
        "caption": caption,
        "command": command,
    }
    if dry_run:
        result["dry_run"] = True
        return result

    result["send_attempts"] = run_gate_send(command)["attempts"]

    fm["status"] = "delivered"
    fm["delivered_at"] = utc_now_iso()
    fm["deliverable"] = str(deliverable)
    item.body = item.body.rstrip() + (
        f"\n\n## {utc_now_iso()}\n\n📦 **Delivered** `{deliverable.name}` to `{config.gate.target}`.\n"
    )
    vault.save(item)

    # Best-effort audit comments; a board hiccup must not un-deliver the item.
    warnings: list[str] = []
    note = f"📦 Delivered `{deliverable.name}` for `{slug}` to `{config.gate.target}`."
    try:
        store = KanbanStore(board_db(config))
        conn = store.connect()
        try:
            for comment_target in {t for t in (first_linked_task(fm), task_id) if t}:
                store.comment(conn, comment_target, author="hermes-triage:delivery", body=note)
            conn.commit()
        finally:
            conn.close()
    except Exception as exc:  # noqa: BLE001 - delivery already succeeded
        warnings.append(f"delivered, but board comment failed: {type(exc).__name__}: {exc}")
    if warnings:
        result["warnings"] = warnings
    return result


def action_send_proposal(
    reference: str,
    config_path: str | Path | None = None,
    *,
    explicit_file: str | None = None,
    dry_run: bool = False,
    task_id: str | None = None,
    resend: bool = False,
) -> dict[str, Any]:
    """Send the rendered proposal to the gate as one attachment message.

    Sets the item to `awaiting_approval` only AFTER the send succeeds, so a
    failed send leaves the item retry-safe. Re-running against an item that is
    already `awaiting_approval` with a recorded send is an idempotent no-op;
    `--resend` overrides that for redrafts.
    """
    config = load_config(config_path)
    slug = item_slug(reference, config)
    vault = ItemVault(vault_dir(config))
    item = vault.load(slug)
    fm = item.frontmatter

    status = fm.get("status")
    if status in PROPOSAL_FORBIDDEN_STATUSES or str(status).startswith("auto_"):
        die_state(
            f"Item {slug} is {status!r}; its gate decision is already made — refusing to (re)send a proposal."
        )
    if status == "awaiting_approval" and fm.get("proposal_sent_at") and not resend:
        return {"ok": True, "action": "send-proposal", "slug": slug, "already_sent": True,
                "proposal_sent_at": fm.get("proposal_sent_at")}
    if not config.gate.target:
        die_state("gate.target is not configured in triage.yaml; nowhere to send the proposal.")

    proposal = resolve_proposal_file(config, slug, explicit_file)
    caption = proposal_caption(config, slug, fm)
    command = gate_send_command(config.gate.target, caption, proposal)
    result: dict[str, Any] = {
        "ok": True,
        "action": "send-proposal",
        "pipeline_id": config.pipeline_id,
        "slug": slug,
        "proposal": str(proposal),
        "target": config.gate.target,
        "caption": caption,
        "command": command,
    }
    if dry_run:
        result["dry_run"] = True
        return result

    result["send_attempts"] = run_gate_send(command)["attempts"]

    fm["status"] = "awaiting_approval"
    fm["proposal_sent_at"] = utc_now_iso()
    fm["proposal_file"] = str(proposal)
    item.body = append_note(
        item.body,
        f"📋 **Proposal sent** to `{config.gate.target}` (attachment: `{proposal.name}`).",
    )
    vault.save(item)

    # Best-effort audit comments; a board hiccup must not un-send the proposal.
    warnings: list[str] = []
    note = f"📋 Proposal for `{slug}` sent to `{config.gate.target}` (attachment: `{proposal.name}`)."
    try:
        store = KanbanStore(board_db(config))
        conn = store.connect()
        try:
            for comment_target in {t for t in (first_linked_task(fm), task_id) if t}:
                store.comment(conn, comment_target, author="hermes-triage:delivery", body=note)
            conn.commit()
        finally:
            conn.close()
    except Exception as exc:  # noqa: BLE001 - the send already succeeded
        warnings.append(f"sent, but board comment failed: {type(exc).__name__}: {exc}")
    if warnings:
        result["warnings"] = warnings
    return result


KNOWN_ACTIONS = ("deliver", "send-proposal")


def _normalize_argv(argv: list[str]) -> list[str]:
    """Insert `deliver` for pre-split invocations (`delivery_actions.py [--config X] <slug>`).

    Live task cards created before send-proposal existed embed the old
    no-subcommand form; they must keep working verbatim.
    """
    out = list(argv)
    i = 0
    while i < len(out):
        token = out[i]
        if token == "--config":
            i += 2
            continue
        if token.startswith("-"):
            i += 1
            continue
        if token not in KNOWN_ACTIONS:
            out.insert(i, "deliver")
        return out
    return out


def main(argv: list[str] | None = None) -> int:
    argv = _normalize_argv(list(sys.argv[1:] if argv is None else argv))
    parser = argparse.ArgumentParser(prog="delivery_actions", description=__doc__)
    parser.add_argument("--config", default=os.environ.get("TRIAGE_CONFIG") or "triage.yaml")
    sub = parser.add_subparsers(dest="action", required=True)

    p_del = sub.add_parser("deliver", help="Send the approved item's deliverable to the gate target.")
    p_del.add_argument("slug", help="Item slug or pipeline-qualified reference (<pipeline>:<slug>).")
    p_del.add_argument("--file", default=None, help="Explicit deliverable path inside the item workspace.")

    p_prop = sub.add_parser("send-proposal", help="Send the rendered proposal to the gate target.")
    p_prop.add_argument("slug", help="Item slug or pipeline-qualified reference (<pipeline>:<slug>).")
    p_prop.add_argument("--file", default=None, help="Explicit proposal path (default: <workspace>/proposals/<slug>.md).")
    p_prop.add_argument("--resend", action="store_true",
                        help="Send even though a proposal was already sent (redrafts).")

    for p in (p_del, p_prop):
        p.add_argument("--task-id", default=os.environ.get("HERMES_KANBAN_TASK"),
                       help="Running task id for the audit comment (dispatcher-injected).")
        p.add_argument("--dry-run", action="store_true",
                       help="Resolve and validate everything; send nothing, mutate nothing.")

    args = parser.parse_args(argv)
    try:
        if args.action == "send-proposal":
            result = action_send_proposal(
                args.slug, args.config,
                explicit_file=args.file, dry_run=args.dry_run, task_id=args.task_id,
                resend=args.resend,
            )
        else:
            result = action_deliver(
                args.slug, args.config,
                explicit_file=args.file, dry_run=args.dry_run, task_id=args.task_id,
            )
    except SystemExit:
        raise
    except (ValueError, FileNotFoundError) as exc:
        die_state(str(exc))
        return 2
    except Exception as exc:  # pragma: no cover - defensive
        die_backend(f"Unhandled error: {type(exc).__name__}: {exc}")
        return 3
    print(json.dumps(result, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
